name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please fill the form below.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproducible
    attributes:
      label: How can we reproduce this?
      description: Please provide a minimal example to reproduce the issue
    validations:
      required: true
  - type: input
    id: libraflow-version
    attributes:
      label: LibraFlow version
      description: What version of LibraFlow are you using?
  - type: dropdown
    id: platforms
    attributes:
      label: Affected Platforms
      description: Please select both the platform you're building from and developing to
      multiple: true
      options:
        - Runtime - Android
        - Runtime - iOS
        - Runtime - Web
        - Build - MacOS
        - Build - Windows
        - Build - Linux
        - Other (please specify)
    validations:
      required: true
  - type: checkboxes
    id: search
    attributes:
      label: Search
      options:
        - label: I did search for other open and closed issues before opening this
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LibraMusic/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    id: ctx
    attributes:
      label: Additional context
      description: Anything else you would like to add
    validations:
      required: false
